# Generated by Django 6.1.1 on 2026-10-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='route_fuels_state_213957_idx')],
                'constraints': [models.UniqueConstraint(fields=('opis_id', 'state', 'city'), name='uniq_station_place')],
            },
        ),
    ]
